import java.awt.event.ItemListener;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
class CBDemo implements ItemListener {
    JLabel jlabSelected;
    JLabel jlabChanged;
    JCheckBox jcbAlpha;
    JCheckBox jcbBeta;
    JCheckBox jcbGamma;

    CBDemo() {
        // Create a new JFrame container.
        JFrame jfrm = new JFrame("Check Boxes");
        // Specify FlowLayout for the layout manager.
        jfrm.setLayout(new FlowLayout());
        // Give the frame an initial size.
        jfrm.setSize(240, 250);
        // Terminate the program when the user closes the application.
        jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Create empty labels.
        jlabSelected = new JLabel("");
        jlabChanged = new JLabel("<none>");
        // Make check boxes.
        jcbAlpha = new JCheckBox("Web");
        jcbBeta = new JCheckBox("Desktop");
        jcbGamma = new JCheckBox("Mobile");
        // Events generated by the check boxes
        // are handled in common by the itemStateChanged()
        // method implemented by CBDemo.
        jcbAlpha.addItemListener(this);
        jcbBeta.addItemListener(this);
        jcbGamma.addItemListener(this);
        // Add check boxes and labels to the content pane.

        jfrm.add(jcbAlpha);
        jfrm.add(jcbBeta);
        jfrm.add(jcbGamma);
        jfrm.add(jlabChanged);
        jfrm.add(jlabSelected);
        // Display the frame.
        jfrm.setVisible(true);
    }

    // This is the handler for the check boxes.
    public void itemStateChanged(ItemEvent ie) {
        String str = "";
        // Obtain a reference to the check box that
        // caused the event.
        JCheckBox cb = (JCheckBox) ie.getItem();
        // Report what check box changed.
        if(cb.isSelected()) {
            jlabChanged.setText(  "Clicked: "+cb.getText());
        } else {
            jlabChanged.setText("Clicked: "+cb.getText());
        }
        // Report all selected boxes.
        if(jcbAlpha.isSelected()) {
            str += "Web ";
        }
        if(jcbBeta.isSelected()) {
            str += "Desktop ";
        }
        if(jcbGamma.isSelected()) {
            str += "Mobile";
        }
        jlabSelected.setText(str);
    }


        public static void main(String args[]) {
            // Create the frame on the event dispatching thread.
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    new CBDemo();
                }
            });
        }
    }

